/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RepositoriesRouteImport } from './routes/repositories'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as FixesRouteImport } from './routes/fixes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeploymentsIndexRouteImport } from './routes/deployments.index'
import { Route as DeploymentsIdRouteImport } from './routes/deployments.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesRoute = RepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const FixesRoute = FixesRouteImport.update({
  id: '/fixes',
  path: '/fixes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsIndexRoute = DeploymentsIndexRouteImport.update({
  id: '/deployments/',
  path: '/deployments/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsIdRoute = DeploymentsIdRouteImport.update({
  id: '/deployments/$id',
  path: '/deployments/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/fixes': typeof FixesRoute
  '/logs': typeof LogsRoute
  '/repositories': typeof RepositoriesRoute
  '/settings': typeof SettingsRoute
  '/deployments/$id': typeof DeploymentsIdRoute
  '/deployments/': typeof DeploymentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/fixes': typeof FixesRoute
  '/logs': typeof LogsRoute
  '/repositories': typeof RepositoriesRoute
  '/settings': typeof SettingsRoute
  '/deployments/$id': typeof DeploymentsIdRoute
  '/deployments': typeof DeploymentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/fixes': typeof FixesRoute
  '/logs': typeof LogsRoute
  '/repositories': typeof RepositoriesRoute
  '/settings': typeof SettingsRoute
  '/deployments/$id': typeof DeploymentsIdRoute
  '/deployments/': typeof DeploymentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/fixes'
    | '/logs'
    | '/repositories'
    | '/settings'
    | '/deployments/$id'
    | '/deployments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/fixes'
    | '/logs'
    | '/repositories'
    | '/settings'
    | '/deployments/$id'
    | '/deployments'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/fixes'
    | '/logs'
    | '/repositories'
    | '/settings'
    | '/deployments/$id'
    | '/deployments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FixesRoute: typeof FixesRoute
  LogsRoute: typeof LogsRoute
  RepositoriesRoute: typeof RepositoriesRoute
  SettingsRoute: typeof SettingsRoute
  DeploymentsIdRoute: typeof DeploymentsIdRoute
  DeploymentsIndexRoute: typeof DeploymentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories': {
      id: '/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixes': {
      id: '/fixes'
      path: '/fixes'
      fullPath: '/fixes'
      preLoaderRoute: typeof FixesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments/': {
      id: '/deployments/'
      path: '/deployments'
      fullPath: '/deployments/'
      preLoaderRoute: typeof DeploymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments/$id': {
      id: '/deployments/$id'
      path: '/deployments/$id'
      fullPath: '/deployments/$id'
      preLoaderRoute: typeof DeploymentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FixesRoute: FixesRoute,
  LogsRoute: LogsRoute,
  RepositoriesRoute: RepositoriesRoute,
  SettingsRoute: SettingsRoute,
  DeploymentsIdRoute: DeploymentsIdRoute,
  DeploymentsIndexRoute: DeploymentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
